# Generated by Django 4.2.7 on 2024-02-17 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="catagory", old_name="crreated_at", new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product", old_name="crreated_at", new_name="created_at",
        ),
        migrations.RemoveField(model_name="catagory", name="trending_product",),
        migrations.AddField(
            model_name="product",
            name="trending",
            field=models.BooleanField(default=False, help_text="0-default, 1-Trending"),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_qty", models.IntegerField()),
                ("created_ata", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ecommerce.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
