# Generated by Django 4.2.7 on 2024-02-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_rename_crreated_at_catagory_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart", old_name="created_ata", new_name="created_at",
        ),
    ]
